nelmio_api_doc:
    documentation:
        info:
            title: Git Adapter
            description: The project  allowing to get simplified information from Git Reference
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
